In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.utils import normalize

Using TensorFlow backend.


In [2]:
# Загрузим DadaSet
boston = keras.datasets.boston_housing
(train_x, train_y), (test_x, test_y) = boston.load_data()

57344/57026 [==============================] - 0s 0us/step


In [3]:
df = pd.DataFrame(train_x)

In [4]:
# Посмотрим на данные
df.describe()

0           1           2   ...          10          11          12
count  404.000000  404.000000  404.000000  ...  404.000000  404.000000  404.000000
mean     3.745111   11.480198   11.104431  ...   18.475990  354.783168   12.740817
std      9.240734   23.767711    6.811308  ...    2.200382   94.111148    7.254545
min      0.006320    0.000000    0.460000  ...   12.600000    0.320000    1.730000
25%      0.081437    0.000000    5.130000  ...   17.225000  374.672500    6.890000
50%      0.268880    0.000000    9.690000  ...   19.100000  391.250000   11.395000
75%      3.674808   12.500000   18.100000  ...   20.200000  396.157500   17.092500
max     88.976200  100.000000   27.740000  ...   22.000000  396.900000   37.970000

[8 rows x 13 columns]

In [5]:
# Проверим тип данных и есть ли пропуски
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       404 non-null    float64
 1   1       404 non-null    float64
 2   2       404 non-null    float64
 3   3       404 non-null    float64
 4   4       404 non-null    float64
 5   5       404 non-null    float64
 6   6       404 non-null    float64
 7   7       404 non-null    float64
 8   8       404 non-null    float64
 9   9       404 non-null    float64
 10  10      404 non-null    float64
 11  11      404 non-null    float64
 12  12      404 non-null    float64
dtypes: float64(13)
memory usage: 41.2 KB


In [6]:
# Нормализуем данные
norm_train_x = normalize(train_x)
norm_test_x = normalize(test_x)

In [183]:
# Создадим слои
model = keras.Sequential()
model.add(keras.layers.Dense(169, activation='relu'))
model.add(keras.layers.Dense(169, activation='relu'))
model.add(keras.layers.Dense(169, activation='relu'))
model.add(keras.layers.Dense(13, activation='relu'))
model.add(keras.layers.Dense(13, activation='relu'))
model.add(keras.layers.Dense(13, activation='relu'))
model.add(keras.layers.Dense(1))

In [184]:
# Компилируем модель
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
              loss=tf.keras.losses.MeanSquaredError(),
              metrics=['mae', 'mse'])

In [185]:
# Обучаем
model.fit(norm_train_x, train_y, epochs=10)

Epoch 1/10
13/13 [==============================] - 0s 3ms/step - loss: 446.4029 - mae: 18.8823 - mse: 446.4029
Epoch 2/10
13/13 [==============================] - 0s 2ms/step - loss: 102.8282 - mae: 7.3274 - mse: 102.8282
Epoch 3/10
13/13 [==============================] - 0s 2ms/step - loss: 78.7199 - mae: 6.4308 - mse: 78.7199
Epoch 4/10
13/13 [==============================] - 0s 2ms/step - loss: 70.9883 - mae: 5.9205 - mse: 70.9883
Epoch 5/10
13/13 [==============================] - 0s 2ms/step - loss: 69.0509 - mae: 5.8582 - mse: 69.0509
Epoch 6/10
13/13 [==============================] - 0s 2ms/step - loss: 64.6051 - mae: 5.6995 - mse: 64.6051
Epoch 7/10
13/13 [==============================] - 0s 2ms/step - loss: 62.3699 - mae: 5.6304 - mse: 62.3699
Epoch 8/10
13/13 [==============================] - 0s 3ms/step - loss: 64.2802 - mae: 5.6340 - mse: 64.2802
Epoch 9/10
13/13 [==============================] - 0s 2ms/step - loss: 64.2756 - mae: 5.6663 - mse: 64.2756
Epoch 10/10
13

In [186]:
# Смотрим какие показатели выдает нам тестовая выборка
test_acc = model.evaluate(norm_test_x,  test_y, verbose=2)

4/4 - 0s - loss: 62.5525 - mae: 5.6868 - mse: 62.5525


In [187]:
# Предсказываем значения тестовой выборки
probability_model = tf.keras.Sequential([model])
predictions = probability_model.predict(norm_test_x)

In [188]:
# Смотрим что получилось
predictions

array([[ 9.7007   ],
       [19.742512 ],
       [24.645226 ],
       [19.073683 ],
       [24.076977 ],
       [21.071697 ],
       [23.680613 ],
       [24.423664 ],
       [23.638052 ],
       [16.588451 ],
       [11.571499 ],
       [21.722115 ],
       [19.39828  ],
       [25.305445 ],
       [14.503034 ],
       [23.299374 ],
       [23.119095 ],
       [20.030865 ],
       [16.49812  ],
       [16.608833 ],
       [15.213529 ],
       [10.106814 ],
       [22.940508 ],
       [22.610779 ],
       [25.78283  ],
       [16.739813 ],
       [22.503815 ],
       [28.98795  ],
       [10.5018015],
       [22.857054 ],
       [20.02051  ],
       [10.913605 ],
       [25.957928 ],
       [22.968328 ],
       [16.57656  ],
       [15.901725 ],
       [18.820105 ],
       [15.686759 ],
       [16.055428 ],
       [26.654982 ],
       [25.512577 ],
       [22.896889 ],
       [16.337818 ],
       [23.09019  ],
       [24.684982 ],
       [24.69657  ],
       [25.92452  ],
       [22.43

In [189]:
test_y

array([ 7.2, 18.8, 19. , 27. , 22.2, 24.5, 31.2, 22.9, 20.5, 23.2, 18.6,
       14.5, 17.8, 50. , 20.8, 24.3, 24.2, 19.8, 19.1, 22.7, 12. , 10.2,
       20. , 18.5, 20.9, 23. , 27.5, 30.1,  9.5, 22. , 21.2, 14.1, 33.1,
       23.4, 20.1,  7.4, 15.4, 23.8, 20.1, 24.5, 33. , 28.4, 14.1, 46.7,
       32.5, 29.6, 28.4, 19.8, 20.2, 25. , 35.4, 20.3,  9.7, 14.5, 34.9,
       26.6,  7.2, 50. , 32.4, 21.6, 29.8, 13.1, 27.5, 21.2, 23.1, 21.9,
       13. , 23.2,  8.1,  5.6, 21.7, 29.6, 19.6,  7. , 26.4, 18.9, 20.9,
       28.1, 35.4, 10.2, 24.3, 43.1, 17.6, 15.4, 16.2, 27.1, 21.4, 21.5,
       22.4, 25. , 16.6, 18.6, 22. , 42.8, 35.1, 21.5, 36. , 21.9, 24.1,
       50. , 26.7, 25. ])

Предсказанные значения более менее похожи на правду. Основное что помогло при обучении модели это использование нескольких метрик. При использовании одной метрики модель просто брала среднее значение с минимальной ошибкой и выдавала его. При использовании нескольких метрик предсказанные начения стали больше походить на правду.

In [191]:
A = tf.constant(train_x)

print(A)

tf.Tensor(
[[1.23247e+00 0.00000e+00 8.14000e+00 ... 2.10000e+01 3.96900e+02
  1.87200e+01]
 [2.17700e-02 8.25000e+01 2.03000e+00 ... 1.47000e+01 3.95380e+02
  3.11000e+00]
 [4.89822e+00 0.00000e+00 1.81000e+01 ... 2.02000e+01 3.75520e+02
  3.26000e+00]
 ...
 [3.46600e-02 3.50000e+01 6.06000e+00 ... 1.69000e+01 3.62250e+02
  7.83000e+00]
 [2.14918e+00 0.00000e+00 1.95800e+01 ... 1.47000e+01 2.61950e+02
  1.57900e+01]
 [1.43900e-02 6.00000e+01 2.93000e+00 ... 1.56000e+01 3.76700e+02
  4.38000e+00]], shape=(404, 13), dtype=float64)


In [192]:
B = tf.constant(test_x)

print(B)

tf.Tensor(
[[1.80846e+01 0.00000e+00 1.81000e+01 ... 2.02000e+01 2.72500e+01
  2.90500e+01]
 [1.23290e-01 0.00000e+00 1.00100e+01 ... 1.78000e+01 3.94950e+02
  1.62100e+01]
 [5.49700e-02 0.00000e+00 5.19000e+00 ... 2.02000e+01 3.96900e+02
  9.74000e+00]
 ...
 [1.83377e+00 0.00000e+00 1.95800e+01 ... 1.47000e+01 3.89610e+02
  1.92000e+00]
 [3.58090e-01 0.00000e+00 6.20000e+00 ... 1.74000e+01 3.91700e+02
  9.71000e+00]
 [2.92400e+00 0.00000e+00 1.95800e+01 ... 1.47000e+01 2.40160e+02
  9.81000e+00]], shape=(102, 13), dtype=float64)


In [197]:
# Сложение тензоров
AB = tf.concat(values=[A[:102],B], axis=1)
print(AB)

tf.Tensor(
[[1.23247e+00 0.00000e+00 8.14000e+00 ... 2.02000e+01 2.72500e+01
  2.90500e+01]
 [2.17700e-02 8.25000e+01 2.03000e+00 ... 1.78000e+01 3.94950e+02
  1.62100e+01]
 [4.89822e+00 0.00000e+00 1.81000e+01 ... 2.02000e+01 3.96900e+02
  9.74000e+00]
 ...
 [2.98500e-02 0.00000e+00 2.18000e+00 ... 1.47000e+01 3.89610e+02
  1.92000e+00]
 [6.12900e-02 2.00000e+01 3.33000e+00 ... 1.74000e+01 3.91700e+02
  9.71000e+00]
 [5.75290e-01 0.00000e+00 6.20000e+00 ... 1.47000e+01 2.40160e+02
  9.81000e+00]], shape=(102, 26), dtype=float64)


In [199]:
# Умножение тензоров
AB2 = tf.multiply(A[:102], B)
print(AB2)

tf.Tensor(
[[2.22887270e+01 0.00000000e+00 1.47334000e+02 ... 4.24200000e+02
  1.08155250e+04 5.43816000e+02]
 [2.68402330e-03 0.00000000e+00 2.03203000e+01 ... 2.61660000e+02
  1.56155331e+05 5.04131000e+01]
 [2.69255153e-01 0.00000000e+00 9.39390000e+01 ... 4.08040000e+02
  1.49043888e+05 3.17524000e+01]
 ...
 [5.47380345e-02 0.00000000e+00 4.26844000e+01 ... 2.74890000e+02
  1.53553093e+05 1.00032000e+01]
 [2.19473361e-02 0.00000000e+00 2.06460000e+01 ... 2.59260000e+02
  1.47698319e+05 2.92271000e+01]
 [1.68214796e+00 0.00000000e+00 1.21396000e+02 ... 2.55780000e+02
  9.26801456e+04 2.42307000e+01]], shape=(102, 13), dtype=float64)


In [201]:
# Ранг тензора
rang_A = tf.rank(A)
print(rang_A.numpy())

2


In [202]:
# Возведение в квадарат
sqr_B = tf.square(B)
print(sqr_B)

tf.Tensor(
[[3.27052757e+02 0.00000000e+00 3.27610000e+02 ... 4.08040000e+02
  7.42562500e+02 8.43902500e+02]
 [1.52004241e-02 0.00000000e+00 1.00200100e+02 ... 3.16840000e+02
  1.55985503e+05 2.62764100e+02]
 [3.02170090e-03 0.00000000e+00 2.69361000e+01 ... 4.08040000e+02
  1.57529610e+05 9.48676000e+01]
 ...
 [3.36271241e+00 0.00000000e+00 3.83376400e+02 ... 2.16090000e+02
  1.51795952e+05 3.68640000e+00]
 [1.28228448e-01 0.00000000e+00 3.84400000e+01 ... 3.02760000e+02
  1.53428890e+05 9.42841000e+01]
 [8.54977600e+00 0.00000000e+00 3.83376400e+02 ... 2.16090000e+02
  5.76768256e+04 9.62361000e+01]], shape=(102, 13), dtype=float64)


In [207]:
# Вычитание
BA = B - A[:102]
print(BA)

tf.Tensor(
[[ 1.685213e+01  0.000000e+00  9.960000e+00 ... -8.000000e-01
  -3.696500e+02  1.033000e+01]
 [ 1.015200e-01 -8.250000e+01  7.980000e+00 ...  3.100000e+00
  -4.300000e-01  1.310000e+01]
 [-4.843250e+00  0.000000e+00 -1.291000e+01 ...  0.000000e+00
   2.138000e+01  6.480000e+00]
 ...
 [ 1.803920e+00  0.000000e+00  1.740000e+01 ... -4.000000e+00
  -4.510000e+00 -3.290000e+00]
 [ 2.968000e-01 -2.000000e+01  2.870000e+00 ...  2.500000e+00
   1.463000e+01  6.700000e+00]
 [ 2.348710e+00  0.000000e+00  1.338000e+01 ... -2.700000e+00
  -1.457500e+02  7.340000e+00]], shape=(102, 13), dtype=float64)
